// import type { Metadata } from "next";
// import {Inter}  from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";
// import  Header  from "@/components/Header";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";
// import Link from "next/link";
// import { Toaster } from "@/components/ui/sonner";


// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
// export const metadata: Metadata = {
//   title: "HyrStack",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider appearance={{
//       baseTheme:dark
//     }
//     }>
//     <html lang="en">
//       <body
//         className={`${inter.variable} antialiased`}
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <Header/>
//           <main className="min-h-screen">{children}</main>
//           <Toaster className="z-50" richColors/>
//           {/* footer */}
//           <footer className="border-t border-white/10  bg-background">
//   <div className="max-w-6xl mx-auto px-6 py-10">
//     <div className="flex flex-col md:flex-row items-center justify-between gap-6">

//       {/* Brand */}
//       <div className="text-center md:text-left">
//         <h3 className="text-lg font-semibold text-white">HyrStack</h3>
//         <p className="text-sm text-white/50 mt-1">
//           AI-powered tools to build your career faster.
//         </p>
//       </div>

//       {/* Links */}
//       <div className="flex items-center gap-6 text-sm text-white/60">
//         <Link href="/privacy" className="hover:text-white transition">
//           Privacy Policy
//         </Link>
//         <Link href="/terms" className="hover:text-white transition">
//           Terms
//         </Link>
//         <Link href="/contact" className="hover:text-white transition">
//           Contact
//         </Link>
//       </div>
//     </div>

//     {/* Bottom line */}
//     <div className="mt-8 text-center text-xs text-white/40">
//       © {new Date().getFullYear()} HyrStack. All rights reserved.
//     </div>
//   </div>
// </footer>

//         </ThemeProvider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "HyrStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster className="z-50" richColors />

            <footer className="border-t border-white/10 bg-background">
              <div className="max-w-6xl mx-auto px-6 py-10">
                <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                  <div className="text-center md:text-left">
                    <h3 className="text-lg font-semibold text-white">
                      HyrStack
                    </h3>
                    <p className="text-sm text-white/50 mt-1">
                      AI-powered tools to build your career faster.
                    </p>
                  </div>

                  <div className="flex items-center gap-6 text-sm text-white/60">
                    <Link href="/privacy">Privacy Policy</Link>
                    <Link href="/terms">Terms</Link>
                    <Link href="/contact">Contact</Link>
                  </div>
                </div>

                <div className="mt-8 text-center text-xs text-white/40">
                  © {new Date().getFullYear()} HyrStack. All rights reserved.
                </div>
              </div>
            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
